''' This Module Handles : 

1. Loading the AI Models ( only once at startup )
2. Texts --> Vectors ( Embeddings )
3. Computing the Cosine Similarity between the Two Vectors
'''

import numpy as np
from sentence_transformers import SentenceTransformer

from app.scoring.normalize import normalize

_model : SentenceTransformer | None = None

def get_model() -> SentenceTransformer:

    global _model 

    if _model is None :
        print("Loading the Model 'paraphrase-MiniLM-Layer3-version2'...")
        _model = SentenceTransformer("paraphrase-MiniLM-L3-v2")
        print("Model Ready !")

    return _model

def get_embedding(text:str) -> np.ndarray:

    # Converts a Piece of Text into a Vector

    # Always Normalize before Embedding
    # Consistent Input --> Consistent Output

    cleaned = normalize(text)

    model = get_model()

    # model.encode() returns shape of a Single String
    # [0] returns the First ( only ) result --> Shape

    embedding = model.encode([cleaned])[0]
    return embedding

def semantic_similarity(text_a:str, text_b:str) -> float:

    '''
    Compute the Semantic Similarity between the Two Pieces of Text
    Return's a Float Number betwee 0 and 1
    0.0 --> Completely Different
    1.0 --> Identical in Meaning
    
    Cosine Similarity : 
    --> Measures the Angle between the Two Vectors
    --> If Vector Points are in the Same Direction --> Same Meaning
    --> Directions Matters, Magnitude Doesn't
    --> This is why it works for Answers of Different Lengths
    '''

    embedding_a = get_embedding(text_a)
    embedding_b = get_embedding(text_b)

    # Cosine Similarity Formula : (A . B ) / ( ||A|| * || B || )

    dot_product = np.dot(embedding_a, embedding_b)
    magnitude_a = np.linalg.norm(embedding_a)
    magnitude_b = np.linalg.norm(embedding_b)

    # Guard Against Division by Zero ( when the Text is Empty )

    if magnitude_a == 0 or magnitude_b == 0:
        return 0.0
    
    similarity = dot_product / (magnitude_a * magnitude_b)

    return float(np.clip(similarity, 0.0, 1.0))


# Quick Test 

if __name__ == "__main__":
    pairs = [
        (
            "Aerodynamics is the study of how air moves around objects",
            "Aerodynamics is why things cut through air smoothly",
            "Should be HIGH (same concept, different words)"
        ),
        (
            "The rudder controls yaw",
            "The rudder controls the yaw of the aircraft",
            "Should be VERY HIGH (almost same sentence)"
        ),
        (
            "The rudder controls yaw",
            "The engine provides thrust to move the aircraft forward",
            "Should be LOW (completely different concept)"
        ),
        (
            "Lift is generated by pressure difference",
            "I don't know the answer",
            "Should be VERY LOW"
        ),
    ]

    print("=" * 60)
    for a, b, label in pairs:
        score = semantic_similarity(a, b)
        print(f"\n  {label}")
        print(f"  A : {a[:60]}")
        print(f"  B : {b[:60]}")
        print(f"  Score : {round(score * 100, 2)}%")
    print("\n" + "=" * 60)